// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/fragments-cockpit-interiors/CinderReactorInterior.tsx": () => import("../components/mockups/fragments-cockpit-interiors/CinderReactorInterior.tsx"),
  "./components/mockups/fragments-cockpit-interiors/EmberBridge.tsx": () => import("../components/mockups/fragments-cockpit-interiors/EmberBridge.tsx"),
  "./components/mockups/fragments-cockpit-interiors/FurnaceCarrierInterior.tsx": () => import("../components/mockups/fragments-cockpit-interiors/FurnaceCarrierInterior.tsx"),
  "./components/mockups/fragments-cockpit-interiors/PrismWarbirdInterior.tsx": () => import("../components/mockups/fragments-cockpit-interiors/PrismWarbirdInterior.tsx"),
  "./components/mockups/fragments-cockpit-interiors/RubyInterceptorInterior.tsx": () => import("../components/mockups/fragments-cockpit-interiors/RubyInterceptorInterior.tsx"),
  "./components/mockups/fragments-enemy-cockpits/CinderReactor.tsx": () => import("../components/mockups/fragments-enemy-cockpits/CinderReactor.tsx"),
  "./components/mockups/fragments-enemy-cockpits/EmberCommand.tsx": () => import("../components/mockups/fragments-enemy-cockpits/EmberCommand.tsx"),
  "./components/mockups/fragments-enemy-cockpits/FurnaceCarrier.tsx": () => import("../components/mockups/fragments-enemy-cockpits/FurnaceCarrier.tsx"),
  "./components/mockups/fragments-enemy-cockpits/PrismWarbird.tsx": () => import("../components/mockups/fragments-enemy-cockpits/PrismWarbird.tsx"),
  "./components/mockups/fragments-enemy-cockpits/RubyInterceptor.tsx": () => import("../components/mockups/fragments-enemy-cockpits/RubyInterceptor.tsx"),
  "./components/mockups/fragments-enemy-sprites/CinderHalo.tsx": () => import("../components/mockups/fragments-enemy-sprites/CinderHalo.tsx"),
  "./components/mockups/fragments-enemy-sprites/EmberFang.tsx": () => import("../components/mockups/fragments-enemy-sprites/EmberFang.tsx"),
  "./components/mockups/fragments-enemy-sprites/FurnaceManta.tsx": () => import("../components/mockups/fragments-enemy-sprites/FurnaceManta.tsx"),
  "./components/mockups/fragments-enemy-sprites/RubyBastion.tsx": () => import("../components/mockups/fragments-enemy-sprites/RubyBastion.tsx"),
  "./components/mockups/fragments-enemy-sprites/SolarWasp.tsx": () => import("../components/mockups/fragments-enemy-sprites/SolarWasp.tsx"),
  "./components/mockups/fragments-hud/Bloom.tsx": () => import("../components/mockups/fragments-hud/Bloom.tsx"),
  "./components/mockups/fragments-hud/Circuit.tsx": () => import("../components/mockups/fragments-hud/Circuit.tsx"),
  "./components/mockups/fragments-hud/Command.tsx": () => import("../components/mockups/fragments-hud/Command.tsx"),
  "./components/mockups/fragments-hud/Prism.tsx": () => import("../components/mockups/fragments-hud/Prism.tsx"),
  "./components/mockups/fragments-hud/Rivet.tsx": () => import("../components/mockups/fragments-hud/Rivet.tsx")
};
