// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/fragments-hud/Bloom.tsx": () => import("../components/mockups/fragments-hud/Bloom.tsx"),
  "./components/mockups/fragments-hud/Circuit.tsx": () => import("../components/mockups/fragments-hud/Circuit.tsx"),
  "./components/mockups/fragments-hud/Command.tsx": () => import("../components/mockups/fragments-hud/Command.tsx"),
  "./components/mockups/fragments-hud/Prism.tsx": () => import("../components/mockups/fragments-hud/Prism.tsx"),
  "./components/mockups/fragments-hud/Rivet.tsx": () => import("../components/mockups/fragments-hud/Rivet.tsx")
};
