name = "fragments-leaderboard"
main = "index.js"
compatibility_date = "2026-09-17"
account_id = "dfbfe5b60929abafcb9629f7aad1dd7d"

[vars]
GITHUB_OWNER = "LioCroust"
GITHUB_REPOSITORY = "fragments-scores"
GITHUB_BRANCH = "main"
ALLOWED_ORIGIN = "*"